<template>
  <div id="app">
    <Navbar />
    <Section heading="Your Data Can" highlight="Cure You" divided>
      <template v-slot:col1>
        <p>
          Reverse aging, extend active lifespan now with Longevity InTime
          <br /><br />
          Early stages prediction & prevention of severe diseases that can
          significantly extend your health span. Powered by artificial
          intelligence, verified by scientists, generated by Big Data obtained
          from evidence based only clinical trials.
        </p>
      </template>
      <template v-slot:col2>
        <img
          src="@/assets/beautiful-young-female-doctor-looking-camera-office-cropped.png"
          alt="young female doctor"
          height="500"
          class="mt-5"
        />
      </template>
    </Section>
    <Section
      id="about"
      heading="What is"
      highlight="Longevity InTime?"
      divided
      reverse
    >
      <template v-slot:col1>
        <p>
          Longevity InTime is a four verticals company developing online
          technologies, which enables early diagnosis of diseases using
          real-time biometrics from your human body to cure you. <br /><br />
          Personal electronic gadgets (smart-watches, fitness-bracelets, etc.),
          portable containers for remote sampling of seven biomaterials (blood,
          urine, etc.), software code, proprietary machine learning algorithms
          and mobile apps help to diagnose and predict the likelihood of
          developing serious diseases in the extremely early, formerly
          diagnosable stages, and provide personalized recommendations for their
          prevention. Early diagnosis of diseases and taking in time the
          necessary measures when they are detected can have a positive effect
          on a person's life expectancy.
        </p>
      </template>
      <template v-slot:col2>
        <img
          src="@/assets/medium-shot-doctor-holding-tablet.png"
          alt="doctor holding tablet"
          height="500"
          class="mt-5"
        />
      </template>
    </Section>
    <Section heading="Awards">
      <template>
        <div class="row">
          <div class="col-md-4">
            <div class="card border-white shado-sm p-1">
              <img
                src="https://www.intime.digital/static/landing/img/award_1_1.png"
                class="card-img-top my-2"
                width="300"
                alt="award1"
              />
              <div class="card-body">
                <h5 class="card-title">Biotechnology Award</h5>
                <p class="card-text">
                  Best Severe Disease Real-Time Remote Tracking Tech Company
                  2021
                </p>
                <a href="#!" class="btn btn-primary">Read more</a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card border-white shado-sm p-1">
              <img
                src="https://www.intime.digital/static/landing/img/award_2.png"
                class="card-img-top my-2"
                width="300"
                alt="award2"
              />
              <div class="card-body">
                <h5 class="card-title">Health & Pharmaceutical Award</h5>
                <p class="card-text">
                  Most Innovative AI Health Tech Company 2020 & Award for
                  Excellence in Disease Tracking Applications 2020
                </p>
                <a href="#!" class="btn btn-primary">Read more</a>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card border-white shado-sm p-1">
              <img
                src="https://www.intime.digital/static/landing/img/award_3_1.png"
                class="card-img-top my-2"
                alt="award3"
              />
              <div class="card-body">
                <h5 class="card-title">Private Healthcare Award</h5>
                <p class="card-text">
                  Best COVID-19 Mobile Application 2021: AntiCoronaVirus
                </p>
                <a href="#!" class="btn btn-primary">Read more</a>
              </div>
            </div>
          </div>
        </div>
      </template>
    </Section>
    <Section id="m-app" heading="Mobile" highlight="App" divided>
      <template v-slot:col1>
        <p>
          The proprietary technology is in beta testing and analyzes today 17
          parameters. We plan to add more than 400 parameters of the physical
          state of the human body for personalized real-time risk assessment
          report. The user receives data on his health status in easy to
          understand mobile application and in his encrypted personal web
          account, as well as personal recommendations aimed at improving his
          health span.
          <br /><br />
          All evidence based risks & recommendation reports are updated due to
          patent pending AI methods as frequent as indicators of parameters
          change. We form your personal digital biobank account with tracking
          history of your parameters.
        </p>

        <img
          class="mb-3"
          src="https://www.intime.digital/static/landing/img/svg/google.svg"
          alt="Google Play Store Logo"
        />
        <img
          class="mb-3 ml-3"
          src="https://www.intime.digital/static/landing/img/svg/apple.svg"
          alt="Apple store logo"
        />
      </template>
      <template v-slot:col2>
        <img
          src="@/assets/18837903-cropped.png"
          height="600"
          class="mt-5"
          alt="hand holding a mobile phone"
        />
      </template>
    </Section>
    <Section heading="Our" highlight="Mission" class="bg-light">
      <template>
        <p>
          The team of 40 developers from 12 countries all over the world working
          on the sweat for equity model is probably the largest biotech company
          in the world. Each and every member of which believes in the company's
          goals and global mission.
          <br /><br />
          Our goal is to extend a person's life by more than 20 active and happy
          years without any restrictions to him. We respond to both the personal
          and public interests of every country on Earth.
          <br /><br />
          We believe that you want to see how your children will raise their
          grandchildren. We intend to deliver you this product InTime!
        </p>
      </template>
    </Section>
    <Section heading="Video">
      <template>
        <agile :autoplay="true" :autoplaySpeed="5000">
          <div class="slide">
            <LazyComponent>
            <iframe
              src="https://www.youtube.com/embed/xQytP22d3sA"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            </LazyComponent>
          </div>

          <div class="slide">
            <LazyComponent>
            <iframe
              src="https://www.youtube.com/embed/1TEYTNI9UEo"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            </LazyComponent>
          </div>
          <div class="slide">
            <LazyComponent>
            <iframe
              src="https://www.youtube.com/embed/TsA4SHhUzt4"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            </LazyComponent>
          </div>
          <div class="slide">
            <LazyComponent>
            <iframe
              src="https://www.youtube.com/embed/IEz1P4i1P7s"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            </LazyComponent>
          </div>
          <div class="slide">
            <LazyComponent>
            <iframe
              src="https://www.youtube.com/embed/yefzqDpJ5Oc"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
            </LazyComponent>
          </div>
        </agile>
      </template>
    </Section>
    <Footer id="contact" class="bg-light" />
    <a href="#about" type="button" class="btn btn-outline-primary d-block to-top" v-smooth-scroll>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        fill="currentColor"
        class="bi bi-arrow-up"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z"
        />
      </svg>
    </a>
  </div>
</template>

<script>
import Navbar from "./components/Navbar.vue";
import Section from "./components/Section.vue";
import Footer from "./components/Footer.vue";

export default {
  name: "App",
  components: {
    Navbar,
    Section,
    Footer,
  },
};
</script>

<style>
#app {
  font-family: "Montserrat", sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  position: relative;
  text-align: center;
  color: #2c3e50;
}

.agile {
  max-width: 850px;
  height: 450px;
  margin: 0 auto;
}

.agile__nav-button--prev {
  top: 45%;
  left: 5px;
}
.agile__nav-button--next {
  top: 45%;
  right: 5px;
}

.agile__nav-button {
  background: #007bff;
  border: none;
  border-radius: 100%;
  color: #fff;
  cursor: pointer;
  font-size: 24px;
  height: 40px;
  position: absolute;
  transition-duration: 0.3s;
  width: 40px;
}
.agile__nav-button:hover {
  background-color: rgba(0, 0, 0, 0.5);
  opacity: 1;
}

.agile__dots {
  bottom: 10px;
  left: 50%;
  position: absolute;
  transform: translateX(-50%);
}
.agile__dot {
  margin: 0 10px;
}
.agile__dot button {
  background-color: transparent;
  border: 1px solid #fff;
  border-radius: 50%;
  cursor: pointer;
  display: block;
  height: 10px;
  font-size: 0;
  line-height: 0;
  margin: 0;
  padding: 0;
  transition-duration: 0.3s;
  width: 10px;
}
.agile__dot--current button,
.agile__dot:hover button {
  background-color: #fff;
}

.slide {
  display: block;
  height: 450px;
  -o-object-fit: cover;
  object-fit: cover;
  /* width: 100% !important; */
}

.slide iframe {
  width: 100%;
  height: 100%;
}

.to-top {
  position: sticky;
  display: block;
  bottom: 20px;
  margin-right: 20px;
  margin-left: auto;
  width: fit-content;
}
</style>
